apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: fees-web
  name: fees-web
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: fees-web
  type: ClusterIP
status:
  loadBalancer: {}